# Generated by Django 5.0.4 on 2024-04-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('seguro', 'Seguro'), ('alquiler', 'Alquiler'), ('servicio', 'Servicio'), ('comida', 'Comida'), ('gasolina', 'Gasolina'), ('carro', 'Carro'), ('condominio', 'Condominio'), ('educacion', 'Educación'), ('ocio', 'Ocio'), ('reparaciones', 'Reparaciones'), ('impuestos', 'Impuestos'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
